package lexer

var SupportedLanguages = map[string]Language{
	".go": Go,
}

type Language struct {
	Name     string
	Literals map[string]Tokenkind
}

var Go = Language{
	Name: "Go",
	Literals: map[string]Tokenkind{
		"break":       KEYWORD,
		"case":        KEYWORD,
		"chan":        KEYWORD,
		"const":       KEYWORD,
		"continue":    KEYWORD,
		"default":     KEYWORD,
		"defer":       KEYWORD,
		"else":        KEYWORD,
		"fallthrough": KEYWORD,
		"for":         KEYWORD,
		"func":        KEYWORD,
		"go":          KEYWORD,
		"goto":        KEYWORD,
		"if":          KEYWORD,
		"import":      KEYWORD,
		"interface":   KEYWORD,
		"map":         KEYWORD,
		"package":     KEYWORD,
		"range":       KEYWORD,
		"return":      KEYWORD,
		"select":      KEYWORD,
		"struct":      KEYWORD,
		"switch":      KEYWORD,
		"type":        KEYWORD,
		"var":         KEYWORD,
		"(":           PUNCT,
		"[":           PUNCT,
		"{":           PUNCT,
		",":           PUNCT,
		".":           PUNCT,
		")":           PUNCT,
		"]":           PUNCT,
		"}":           PUNCT,
		";":           PUNCT,
		":":           PUNCT,
		"+":           OPERATOR,
		"-":           OPERATOR,
		"*":           OPERATOR,
		"/":           OPERATOR,
		"%":           OPERATOR,
		"&":           OPERATOR,
		"|":           OPERATOR,
		"^":           OPERATOR,
		"<<":          OPERATOR,
		">>":          OPERATOR,
		"&^":          OPERATOR,
		"+=":          OPERATOR,
		"-=":          OPERATOR,
		"*=":          OPERATOR,
		"/=":          OPERATOR,
		"%=":          OPERATOR,
		"&=":          OPERATOR,
		"|=":          OPERATOR,
		"^=":          OPERATOR,
		"<<=":         OPERATOR,
		">>=":         OPERATOR,
		"&^=":         OPERATOR,
		"&&":          OPERATOR,
		"||":          OPERATOR,
		"<-":          OPERATOR,
		"++":          OPERATOR,
		"--":          OPERATOR,
		"==":          OPERATOR,
		"<":           OPERATOR,
		">":           OPERATOR,
		"=":           OPERATOR,
		"!":           OPERATOR,
		"!=":          OPERATOR,
		"<=":          OPERATOR,
		">=":          OPERATOR,
		":=":          OPERATOR,
		"...":         OPERATOR,
	},
}
